awk '/\/\* Diagnostic Wizard Button \*\// { 
  print "          {/* Duplicate File Finder Button */}"
  print "          {onOpenDuplicateFileFinder && ("
  print "            <button"
  print "              onClick={onOpenDuplicateFileFinder}"
  print "              className=\"flex items-center space-x-1 bg-slate-800 hover:bg-slate-700 text-blue-300 text-xs px-2.5 py-1.5 rounded-lg border border-slate-700 transition font-medium shrink-0\""
  print "              title=\"Skaner Zduplikowanych Plików\""
  print "            >"
  print "              <Search className=\"w-3.5 h-3.5 text-blue-400\" />"
  print "              <span className=\"hidden lg:inline\">Usuń Duplikaty</span>"
  print "            </button>"
  print "          )}"
  print "          {/* Spell Checker Button */}"
  print "          {onOpenSpellChecker && ("
  print "            <button"
  print "              onClick={onOpenSpellChecker}"
  print "              className=\"flex items-center space-x-1 bg-slate-800 hover:bg-slate-700 text-purple-300 text-xs px-2.5 py-1.5 rounded-lg border border-slate-700 transition font-medium shrink-0\""
  print "              title=\"Automatyczna Poprawa Pisowni\""
  print "            >"
  print "              <Wand2 className=\"w-3.5 h-3.5 text-purple-400\" />"
  print "              <span className=\"hidden lg:inline\">Poprawa Pisowni</span>"
  print "            </button>"
  print "          )}"
  print "          {/* Mobile SMS App Button */}"
  print "          {onOpenMobileSmsApp && ("
  print "            <button"
  print "              onClick={onOpenMobileSmsApp}"
  print "              className=\"flex items-center space-x-1 bg-emerald-600/20 hover:bg-emerald-600/30 text-emerald-300 text-xs px-2.5 py-1.5 rounded-lg border border-emerald-500/30 transition font-medium shrink-0\""
  print "              title=\"Bramka SMS na Androida\""
  print "            >"
  print "              <Smartphone className=\"w-3.5 h-3.5 text-emerald-400\" />"
  print "              <span className=\"hidden lg:inline\">Bramka SMS</span>"
  print "            </button>"
  print "          )}"
} 1' src/components/Header.tsx > src/components/Header.tsx.tmp && mv src/components/Header.tsx.tmp src/components/Header.tsx
